export enum EnvVariableName {
    PORT = 'PORT',
    ACCESS_TOKEN_EXPIRES_IN = 'ACCESS_TOKEN_EXPIRES_IN',
    REFRESH_TOKEN_EXPIRES_IN = 'REFRESH_TOKEN_EXPIRES_IN',
    ACCESS_TOKEN_SECRET = 'ACCESS_TOKEN_SECRET',
    REFRESH_ACCESS_TOKEN_SECRET = 'REFRESH_ACCESS_TOKEN_SECRET',
    FRONTEND_URL = 'FRONTEND_URL',
    MONGODB_URI = 'MONGODB_URI',
}
